var seriesData = [
    { name: '北京', value: 100, alias: 'beijing' },
    { name: '天津', value: 10, alias: 'tianjin' },
    { name: '上海', value: 60, alias: 'shanghai' },
    { name: '重庆', value: 0, alias: 'chongqing' },
    { name: '河北', value: 60, alias: 'hebei' },
    { name: '河南', value: 60, alias: 'henan' },
    { name: '云南', value: 0, alias: 'yunnan' },
    { name: '辽宁', value: 0, alias: 'liaoning' },
    { name: '黑龙江', value: 0, alias: 'heilongjiang' },
    { name: '湖南', value: 60, alias: 'hunan' },
    { name: '安徽', value: 0, alias: 'anhui' },
    { name: '山东', value: 60, alias: 'shandong' },
    { name: '新疆', value: 0, alias: 'xinjiang' },
    { name: '江苏', value: 0, alias: 'jiangsu' },
    { name: '浙江', value: 0, alias: 'zhejiang' },
    { name: '江西', value: 0, alias: 'jiangxi' },
    { name: '湖北', value: 60, alias: 'hubei' },
    { name: '广西', value: 60, alias: 'guangxi' },
    { name: '甘肃', value: 0, alias: 'gansu' },
    { name: '山西', value: 60, alias: 'shanxi' },
    { name: '内蒙古', value: 0, alias: 'neimenggu' },
    { name: '陕西', value: 0, alias: 'shanxi' },
    { name: '吉林', value: 0, alias: 'jilin' },
    { name: '福建', value: 0, alias: 'fujian' },
    { name: '贵州', value: 0, alias: 'guizhou' },
    { name: '广东', value: 597, alias: 'guangdong' },
    { name: '青海', value: 0, alias: 'qinghai' },
    { name: '西藏', value: 0, alias: 'xizang' },
    { name: '四川', value: 60, alias: 'sichuan' },
    { name: '宁夏', value: 0, alias: 'ningxia' },
    { name: '海南', value: 60, alias: 'hainan' },
    { name: '台湾', value: 0, alias: 'taiwan' },
    { name: '香港', value: 0, alias: 'xianggang' },
    { name: '澳门', value: 0, alias: 'aomen' }];


var seriesHebeiData = [
    { name: '张家口市', value: 10 },
    { name: '承德市', value: 10 },
    { name: '秦皇岛市', value: 10 },
    { name: '唐山市', value: 10 },
    { name: '保定市', value: 10 },
    { name: '石家庄市', value: 10 },
    { name: '衡水市', value: 10 },
    { name: '邢台市', value: 10 },
    { name: '邯郸市', value: 10 },
    { name: '沧州市', value: 10 },
    { name: '廊坊市', value: 10 },
];