###

# 博客创建
POST http://localhost:3000/api/blog/new
Content-Type: application/json

{
    "title": "创建文章标题",
    "content": "创建文章内容"
}

###

# 博客更新
POST http://localhost:3000/api/blog/update?id=3
Content-Type: application/json

{
    "title": "标题C",
    "content": "内容C"
}

###

# 博客删除
POST http://localhost:3000/api/blog/delete?id=4
